github: MoloBTC-Org
custom:
  - "https://www.MoloBTC.africa"
  - "lightning:copperpuma28@primal.net"
  - "bitcoin:bc1pluhlkz8mcjkflmzl6l6jrl6ez8rj3mner50xwd9n2942vfvctj4sdgrurq"
  - "nostr:npub1jvcg9k658yg9y8asx78wg05vm5tta2ckwumanqkgjuwkvk4x95uss8l6au"